### ISSUE TITLE
A lot of packages are not displayed in update list

### ISSUE THREAD

**Issue by ckotte** [RaphaelRochet/arch-update#157] opened 2020-12-02 13:10 UTC
The list is indeed 306 lines long, but only 156 lines are displayed. The remaining lines are "hidden":

![image](https://user-images.githubusercontent.com/8488565/100875766-bde44000-34a6-11eb-9ec5-ef9a3fa45796.png)

I can scroll until the end of the list:

![image](https://user-images.githubusercontent.com/8488565/100876574-db65d980-34a7-11eb-8b9d-c5ab3335defa.png)

**Comment by RaphaelRochet** [comment] 2020-12-02 13:22
Looks like dupe of #156 , fixed today in master. You can install from git to have the fix now, of wait for a release.
Thanks for the report anyway ;)

**Closed by RaphaelRochet** 2020-12-02 13:22 UTC

**Comment by Strykar** [comment] 2021-02-22 06:48
Unsure if it's related, but with an Nvidia GPU, I get a blank list every time after a suspend.
@RaphaelRochet Could we get a new release with this fix?

**Comment by RaphaelRochet** [comment] 2021-02-22 07:06
Damned, should have released this long ago ! Will do it ASAP

**Comment by RaphaelRochet** [comment] 2021-02-22 08:57
Done ! Waiting to be reviewed by GNOME team.
