### ISSUE TITLE
Incompatibility with Gnome 46 (beta)

### ISSUE THREAD

**Issue by ydaveluy** [RaphaelRochet/arch-update#231] opened 2024-03-06 08:07 UTC
Hello,

I tested this extension on Gnome 46 (beta) and it raises a TypeError: this.checkingMenuItem.actor.add_actor is not a function
I think that it comes from:
https://github.com/RaphaelRochet/arch-update/blob/967add5f20c1b86716571048080285d5a17f2a49/extension.js#L131

**Comment by RaphaelRochet** [comment] 2024-03-06 08:13
I can't believe they manage to break extensions on each and every release. 
Like always, will test and (hopefully) fix when it will hit Arch's repos. Any ideas when the release is planned ?

**Comment by ydaveluy** [comment] 2024-03-06 09:57
It should be out on 20 March

**Comment by RaphaelRochet** [comment] 2024-03-08 08:41
Looks like I can reproduce with gnome-shell beta from gnome-unstable repo. Will see if this is an easy fix.

**Comment by RaphaelRochet** [comment] 2024-03-08 09:25
Fixed this one, but now blocking on MessageTray.SystemNotificationSource change :tired_face:

**Comment by RaphaelRochet** [comment] 2024-03-08 10:16
Ok, done too. Looks promisin :) Only a little bug left !

**Comment by RaphaelRochet** [comment] 2024-03-08 10:53
Ready for testing (branch Gnome46). Let's hop I caught all bugs. Tell me :)

**Comment by ydaveluy** [comment] 2024-03-09 12:18
Yes everything seems fixed, no issue on my side after few updates

**Comment by Kerrung** [comment] 2024-03-09 16:51
It doesn't work for me on GNOME 46 from [gnome-unstable].
![Screenshot from 2024-03-09 21-31-35](https://github.com/RaphaelRochet/arch-update/assets/36989404/e1bf6eed-86ab-40c5-85cf-15b97900058d)

**Comment by RaphaelRochet** [comment] 2024-03-09 16:53
Ok, disable the manual ordering thin in the options, should work.

**Comment by Kerrung** [comment] 2024-03-09 17:07
> Ok, disable the manual ordering thin in the options, should work.

I didn't realise what exactly I should disable. Can you please send me a screenshot of this particular setting or at least tell me its exact name? Or maybe it would be better to make your extension work with any enabled settings as it was before?

**Comment by RaphaelRochet** [comment] 2024-03-09 17:11
It's the option that allow you to set indicator position. Of course I will have to fix this bug. I may remove that feature altogether if needed.

**Comment by Kerrung** [comment] 2024-03-09 17:15
> It's the option that allow you to set indicator position. Of course I will have to fix this bug. I may remove that feature altogether if needed.

This feature is very much needed to use. I would like to keep it working, please.

**Comment by RaphaelRochet** [comment] 2024-03-11 07:22
That was an easy fix. But I found another bug on notifications (related to new notification management in 46). Working on it.

**Comment by RaphaelRochet** [comment] 2024-03-11 10:20
A few fixes later (, all seems to work fine. More testing may be a good thing if you don't mind.
56858bc030850b1961047a6b23271296ecbd37d6, ea2de9e1cd79341f46d415657ecebe507ad15026, dc78270c00743b22e9c2e3145ae2e73a71f4e706

**Comment by grg3** [comment] 2024-03-24 09:56
46 just hit Arch! 
Thankfully, this extension is still working even though it reports an error: 
Error: Extension point conflict: there is already a status indicator for role ArchUpdateIndicator

**Comment by RaphaelRochet** [comment] 2024-03-24 10:05
I can't reproduce this error. Do you have any more info ?

**Comment by Neo-29** [comment] 2024-03-24 16:41
I've  got a issue here
- no numbers next to the icon
- Can't access the update details at all 

I've got for example six pending updates but if I click on it nothing
[image](https://github.com/RaphaelRochet/arch-update/assets/90937180/6fc2b56d-0ae9-4874-9ca2-42664af3b15c)

**Comment by RaphaelRochet** [comment] 2024-03-24 17:04
I can't reproduce this either. That's annoying. Another extension messing with indicators maybe ?

**Comment by Neo-29** [comment] 2024-03-24 17:06
Can't say... It was working properly with the same extensions on.
I'll investigate.

**Comment by Neo-29** [comment] 2024-03-24 17:14
The AUR package is broken too

**Comment by RaphaelRochet** [comment] 2024-03-24 17:19
Flag it, can't do much about it. Hope the maintainer will update it quickly.

**Comment by Neo-29** [comment] 2024-03-24 17:20
Got it...

That must be off otherwise the issue occurs

![image](https://github.com/RaphaelRochet/arch-update/assets/90937180/86eb0580-50e7-4c80-ad3c-f4fe64844d12)

**Comment by RaphaelRochet** [comment] 2024-03-24 17:26
Ok. I could reproduce this with an error "JS ERROR: TypeError: this.menuExpander.menu.box.add is not a function".
Will fix that, should be an easy fix.

**Comment by RaphaelRochet** [comment] 2024-03-24 17:50
Should be fixed in Master branch ;)
I caught another error in the meanwhile :grin:

**Comment by Neo-29** [comment] 2024-03-24 18:06
> Should be fixed in Master branch ;) I caught another error in the meanwhile 😁

Nice!

I'll wait for the extension to be pushed on the site

**Closed** 2024-04-04 04:50 UTC
