### ISSUE TITLE
Glitches in update menu (v48)

### ISSUE THREAD

**Issue by drakkar1969** [RaphaelRochet/arch-update#192] opened 2022-08-09 07:23 UTC
I just updated to v48, and I noticed some glitches in how available updates are displayed in the indicator menu.

I check for both pacman and AUR updates with the following command:

```
/usr/bin/bash -c 'checkupdates; paru -Qqua'
```

This is the raw output of the check command in terminal:

```
nspr 4.34-1 -> 4.34.1-1
numix-icon-theme-git
```

With the new output parsing enabled, AUR updates are not included in the update count (and are shown in bold):

![new](https://user-images.githubusercontent.com/18715287/183588213-13aa7aca-3579-4a45-953b-9e01f0245fbd.png)

If I disable output parsing (old behavior), AUR updates are correctly counted, but version numbers are not stripped from pacman updates (I have the `Strip out versions numbers` enabled for both indicator and notifications:

![old](https://user-images.githubusercontent.com/18715287/183588527-4db6dd2f-3e55-4b32-8912-63208ee11f3f.png)

**EDIT:**

If I modify the update command to display version numbers with paru (`/usr/bin/bash -c 'checkupdates; paru -Qua'`), the raw output is:

```
nspr 4.34-1 -> 4.34.1-1
numix-icon-theme-git 21.10.31.r13.g7d382d38b-1 -> latest-commit
```

In this case, updates are counted correctly in all cases, but version number are still not stripped out when output parsing is disabled (old behavior):

![mod](https://user-images.githubusercontent.com/18715287/183591342-b0e12e73-71c5-40d3-a0e9-ac94ce368664.png)

**Comment by RaphaelRochet** [comment] 2022-08-09 13:48
Thanks for taking the time to document the issue.
I understand  the issue is that with "old behavior" enabled, version numbers are not stripped in the menu. I could reproduce it indeed. Will fix asap.

**Comment by drakkar1969** [comment] 2022-08-09 14:29
Thanks for looking into it.

In addition to the issue with version numbers not being stripped, I think there is a second issue with available updates not being picked up if they are listed without version numbers when the new parsing option is enabled.

I have downgraded a random pacman package to test this.

**Test 1**

For example, if I use only paru to check for updates with `paru- Qqu`, I get this raw output in terminal:

```
dconf-editor
```

But the updates indicator shows no available updates with the same command,  when parsing output is enabled. If I disable output parsing, the indicator menu correctly lists `dconf-editor` as available update.

**Test 2**

If change the check command to `paru -Qu` (i.e. remove the quiet option), the terminal output is:

```
dconf-editor 3.38.3-1 -> 3.38.3-2
```

The indicator shows `dconf-editor` as an available update with output parsing both enabled and disabled (but as per the other issue, does not strip version numbers with the old behavior)

**Comment by RaphaelRochet** [comment] 2022-08-09 14:36
Yes it is intended with the new parsing system for anything not like "name version -> version" to be considered as a title and not an update. That's why I added a setting to disable this parsing. This offers the ability to add titles in the output (like Official / AUR, or even remote machines).

**Comment by drakkar1969** [comment] 2022-08-09 14:37
> Yes it is intended with the new parsing system for anything not like "name version -> version" to be considered as a title and not an update. That's why I added a setting to disable this parsing. This offers the ability to add titles in the output (like Official / AUR, or even remote machines).

Ok, thanks for clarifying, makes sense now

**Comment by drakkar1969** [comment] 2022-08-09 19:55
Kudos on the new output parsing, btw, been messing with it a bit and really does allow for some more interesting info display

**Comment by RaphaelRochet** [comment] 2022-08-10 11:43
That is now fixed ;)

**Closed by RaphaelRochet** 2022-08-10 11:43 UTC
